# -*- coding: utf-8 -*-
"""Student_Analytics_Using 3 Models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1392ZJGy0SOhRIgCsQ1d3oqZatYRQs4Za
"""

# Commented out IPython magic to ensure Python compatibility.
# 1. Import libraries

# %pip install streamlit
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")
# Machine Learning Imports

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

# Set a simple chart style
sns.set_style("whitegrid")

print("Libraries imported successfully!")

# 2. Load Excel file

# Change this path if your Excel file is in another location
file_path = r"C:\Users\YASHANTU AWANA\OneDrive\Desktop\Major\master_dataset.xlsx"

# Read the Excel file
student_df = pd.read_excel(file_path)

print("Data loaded successfully!")
print("Dataset Shape:", student_df.shape)

# Show the first 5 rows
student_df.head()

# Show the last 5 rows
student_df.tail()

# 3. Explore the dataset

print("Column Names:")
print(student_df.columns.tolist())

print("\nDataset Information:")
student_df.info()

print("\nMissing Values:")
print(student_df.isnull().sum())

print("\nDuplicate Rows:", student_df.duplicated().sum())

# 4. Clean column names

# Remove extra spaces from column names
student_df.columns = student_df.columns.str.strip()

print("Cleaned column names:")
print(student_df.columns.tolist())

# 5. Convert important columns to numbers

# These are the columns we normally use for calculations.
# The code only converts a column if it exists in the dataset.

numeric_columns = [
    "Attendance (%)",
    "Attendance",
    "Fees Paid ($)",
    "Fees Paid",
    "Fees Due ($)",
    "Fees Due",
    "Total Fees ($)",
    "Total Fees",
    "Mid-Term Marks",
    "Mid Term",
    "End-Term Marks",
    "End Term",
    "Assignment Marks",
    "Assignment",
    "Practical Marks",
    "Practical",
    "Total Marks (%)",
    "Total Marks"
]

for column in numeric_columns:
    if column in student_df.columns:
        student_df[column] = pd.to_numeric(
            student_df[column],
            errors="coerce"
        )

print("Numeric columns checked and converted.")

# 6. Create simple helper columns

# Use the correct marks column from the dataset
marks_column = None

for column in ["Total Marks (%)", "Total Marks"]:
    if column in student_df.columns:
        marks_column = column
        break

# Use the correct attendance column
attendance_column = None

for column in ["Attendance (%)", "Attendance"]:
    if column in student_df.columns:
        attendance_column = column
        break

print("Marks column:", marks_column)
print("Attendance column:", attendance_column)

# 7. Create Pass/Fail column

if marks_column is not None:
    student_df["Pass_Fail"] = np.where(
        student_df[marks_column] >= 50,
        "Pass",
        "Fail"
    )

    print(student_df[[marks_column, "Pass_Fail"]].head())
else:
    print("Marks column was not found.")

# 8. Create Low Attendance column

if attendance_column is not None:
    student_df["Low_Attendance"] = np.where(
        student_df[attendance_column] < 75,
        1,
        0
    )

    print(student_df[[attendance_column, "Low_Attendance"]].head())
else:
    print("Attendance column was not found.")

# 9. Create At-Risk column

# A student is At-Risk if:
# - Attendance is below 75%, OR
# - Marks are below 50%

if attendance_column is not None and marks_column is not None:
    student_df["At_Risk"] = np.where(
        (student_df[attendance_column] < 75) |
        (student_df[marks_column] < 50),
        1,
        0
    )

    print(student_df[["At_Risk"]].head())
else:
    print("Attendance or marks column was not found.")

# 10. Basic student statistics

print("===== STUDENT STATISTICS =====")

print("Total Records:", len(student_df))

if "Student Name" in student_df.columns:
    print("Unique Students:", student_df["Student Name"].nunique())

if "Course" in student_df.columns:
    print("Total Courses:", student_df["Course"].nunique())

if "Academic Year" in student_df.columns:
    print("Academic Years:", student_df["Academic Year"].nunique())

if attendance_column is not None:
    print(
        "Average Attendance:",
        round(student_df[attendance_column].mean(), 2),
        "%"
    )

if marks_column is not None:
    print(
        "Average Marks:",
        round(student_df[marks_column].mean(), 2),
        "%"
    )

if "Pass_Fail" in student_df.columns:
    pass_rate = (
        student_df["Pass_Fail"].eq("Pass").mean() * 100
    )
    print("Pass Rate:", round(pass_rate, 2), "%")

# 11. Students by course

if "Course" in student_df.columns:
    students_by_course = student_df["Course"].value_counts()

    print("Students by Course:")
    print(students_by_course)
else:
    print("Course column was not found.")

# 12. Chart: Students by course

if "Course" in student_df.columns:
    student_df["Course"].value_counts().plot(
        kind="bar",
        figsize=(10, 5)
    )

    plt.title("Number of Students by Course")
    plt.xlabel("Course")
    plt.ylabel("Number of Students")
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

# 13. Students by academic year

if "Academic Year" in student_df.columns:
    students_by_year = (
        student_df["Academic Year"]
        .value_counts()
        .sort_index()
    )

    print(students_by_year)
else:
    print("Academic Year column was not found.")

# 14. Chart: Students by academic year

if "Academic Year" in student_df.columns:
    student_df["Academic Year"].value_counts().sort_index().plot(
        kind="bar",
        figsize=(8, 5)
    )

    plt.title("Students by Academic Year")
    plt.xlabel("Academic Year")
    plt.ylabel("Number of Students")
    plt.tight_layout()
    plt.show()

# 15. Students by semester

if "Semester" in student_df.columns:
    semester_count = student_df["Semester"].value_counts()

    print(semester_count)

    semester_count.plot(
        kind="pie",
        autopct="%1.1f%%",
        figsize=(7, 7)
    )

    plt.title("Students by Semester")
    plt.ylabel("")
    plt.show()

# 16. Grade distribution

if "Grade" in student_df.columns:
    grade_counts = student_df["Grade"].value_counts()

    print("Grade Distribution:")
    print(grade_counts)

    grade_counts.plot(
        kind="bar",
        figsize=(8, 5)
    )

    plt.title("Grade Distribution")
    plt.xlabel("Grade")
    plt.ylabel("Number of Students")
    plt.tight_layout()
    plt.show()

# 17. Average marks by course

if "Course" in student_df.columns and marks_column is not None:
    average_marks_course = (
        student_df.groupby("Course")[marks_column]
        .mean()
        .sort_values(ascending=False)
    )

    print(average_marks_course)

    average_marks_course.plot(
        kind="bar",
        figsize=(10, 5)
    )

    plt.title("Average Marks by Course")
    plt.xlabel("Course")
    plt.ylabel("Average Marks (%)")
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

# 18. Average attendance by course

if "Course" in student_df.columns and attendance_column is not None:
    average_attendance_course = (
        student_df.groupby("Course")[attendance_column]
        .mean()
        .sort_values(ascending=False)
    )

    print(average_attendance_course)

    average_attendance_course.plot(
        kind="bar",
        figsize=(10, 5)
    )

    plt.title("Average Attendance by Course")
    plt.xlabel("Course")
    plt.ylabel("Average Attendance (%)")
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

# 19. Pass and Fail analysis

if "Pass_Fail" in student_df.columns:
    pass_fail_count = student_df["Pass_Fail"].value_counts()

    print(pass_fail_count)

    pass_fail_count.plot(
        kind="pie",
        autopct="%1.1f%%",
        figsize=(7, 7)
    )

    plt.title("Pass vs Fail Students")
    plt.ylabel("")
    plt.show()

# 20. Attendance analysis

if attendance_column is not None:
    attendance_status = np.where(
        student_df[attendance_column] < 75,
        "Low Attendance",
        "Normal Attendance"
    )

    attendance_count = pd.Series(
        attendance_status
    ).value_counts()

    print(attendance_count)

    attendance_count.plot(
        kind="bar",
        figsize=(7, 5)
    )

    plt.title("Attendance Status")
    plt.xlabel("Attendance Status")
    plt.ylabel("Number of Students")
    plt.tight_layout()
    plt.show()

# 21. At-Risk student analysis

if "At_Risk" in student_df.columns:
    risk_status = np.where(
        student_df["At_Risk"] == 1,
        "At-Risk",
        "Performing"
    )

    risk_count = pd.Series(
        risk_status
    ).value_counts()

    print(risk_count)

    risk_count.plot(
        kind="bar",
        figsize=(7, 5)
    )

    plt.title("Student Risk Analysis")
    plt.xlabel("Student Status")
    plt.ylabel("Number of Students")
    plt.tight_layout()
    plt.show()

# 22. Top 10 Students

if "Student Name" in student_df.columns and marks_column is not None:

    # Sort students by marks from highest to lowest
    top_students = (
        student_df
        .sort_values(
            by=marks_column,
            ascending=False
        )
        .head(10)
    )

    # Select columns to display
    columns_to_show = [
        column for column in [
            "Student Name",
            "Course",
            marks_column,
            "Grade"
        ]
        if column in top_students.columns
    ]

    # Display Top 10 Students
    print("Top 10 Performing Students:")
    print("=" * 50)

    display(
        top_students[columns_to_show]
    )

else:
    print("Student Name or Marks column was not found.")

# 23. Students Needing Academic Improvement

if marks_column is not None:

    # Find students with marks below 50
    weak_students = student_df[
        student_df[marks_column] < 50
    ]

    # Select columns to display
    columns_to_show = [
        "Student Name",
        "Course",
        marks_column
    ]

    # Add attendance if available
    if attendance_column is not None:
        columns_to_show.append(attendance_column)

    # Display the result
    print("Students Needing Academic Improvement:")
    print("=" * 50)

    display(
        weak_students[columns_to_show].head(20)
    )

else:
    print("Marks column was not found.")

# 24. Fee analysis

# This section works if fee columns exist in your dataset.

fee_paid_column = next(
    (
        column for column in [
            "Fees Paid ($)",
            "Fees Paid"
        ]
        if column in student_df.columns
    ),
    None
)

fee_due_column = next(
    (
        column for column in [
            "Fees Due ($)",
            "Fees Due"
        ]
        if column in student_df.columns
    ),
    None
)

total_fee_column = next(
    (
        column for column in [
            "Total Fees ($)",
            "Total Fees"
        ]
        if column in student_df.columns
    ),
    None
)

if total_fee_column and fee_paid_column:
    student_df["Calculated_Fees_Due"] = (
        student_df[total_fee_column]
        - student_df[fee_paid_column]
    )

    print("Total Fees:",
          student_df[total_fee_column].sum())

    print("Total Fees Paid:",
          student_df[fee_paid_column].sum())

    print("Total Fees Due:",
          student_df["Calculated_Fees_Due"].sum())
else:
    print("Fee columns were not found.")

# 25. Fee payment status

if "Calculated_Fees_Due" in student_df.columns:
    student_df["Fee_Status"] = np.where(
        student_df["Calculated_Fees_Due"] <= 0,
        "Fully Paid",
        "Payment Due"
    )

    fee_status_count = student_df[
        "Fee_Status"
    ].value_counts()

    print(fee_status_count)

    fee_status_count.plot(
        kind="pie",
        autopct="%1.1f%%",
        figsize=(7, 7)
    )

    plt.title("Fee Payment Status")
    plt.ylabel("")
    plt.show()

# 26. Marks distribution

if marks_column is not None:
    plt.figure(figsize=(8, 5))

    plt.hist(
        student_df[marks_column].dropna(),
        bins=10
    )

    plt.title("Distribution of Total Marks")
    plt.xlabel("Total Marks (%)")
    plt.ylabel("Number of Students")
    plt.show()

# 27. Attendance distribution

if attendance_column is not None:
    plt.figure(figsize=(8, 5))

    plt.hist(
        student_df[attendance_column].dropna(),
        bins=10
    )

    plt.title("Distribution of Student Attendance")
    plt.xlabel("Attendance (%)")
    plt.ylabel("Number of Students")
    plt.show()

# 28. Attendance vs Marks

if attendance_column is not None and marks_column is not None:
    plt.figure(figsize=(8, 5))

    plt.scatter(
        student_df[attendance_column],
        student_df[marks_column]
    )

    plt.title("Attendance vs Total Marks")
    plt.xlabel("Attendance (%)")
    plt.ylabel("Total Marks (%)")
    plt.show()

# 29. Correlation between attendance and marks

if attendance_column is not None and marks_column is not None:
    correlation = student_df[
        attendance_column
    ].corr(
        student_df[marks_column]
    )

    print(
        "Correlation between Attendance and Marks:",
        round(correlation, 2)
    )

    if correlation > 0:
        print("There is a positive relationship.")
    elif correlation < 0:
        print("There is a negative relationship.")
    else:
        print("There is no clear relationship.")

# 30. Average marks by academic year

if "Academic Year" in student_df.columns and marks_column is not None:
    yearly_marks = (
        student_df.groupby("Academic Year")[marks_column]
        .mean()
    )

    print(yearly_marks)

    yearly_marks.plot(
        kind="line",
        marker="o",
        figsize=(8, 5)
    )

    plt.title("Average Marks by Academic Year")
    plt.xlabel("Academic Year")
    plt.ylabel("Average Marks (%)")
    plt.show()

# 31. Average attendance by academic year

if "Academic Year" in student_df.columns and attendance_column is not None:
    yearly_attendance = (
        student_df.groupby("Academic Year")[attendance_column]
        .mean()
    )

    print(yearly_attendance)

    yearly_attendance.plot(
        kind="line",
        marker="o",
        figsize=(8, 5)
    )

    plt.title("Average Attendance by Academic Year")
    plt.xlabel("Academic Year")
    plt.ylabel("Average Attendance (%)")
    plt.show()

print(student_df.columns.tolist())

# 32. Student Performance Summary

# Check available columns
print("Available columns:")
print(student_df.columns.tolist())

# Check if Course column exists
if "Course" in student_df.columns:

    # Create summary
    performance_summary = (
        student_df
        .groupby("Course")
        .agg(
            Total_Students=("Student Name", "count"),
            Average_Marks=(marks_column, "mean"),
            Average_Attendance=(attendance_column, "mean")
        )
        .round(2)
    )

    # Display summary
    print("\nStudent Performance Summary:")
    display(performance_summary)

else:
    print(
        "Error: 'Course' column was not found."
    )

# 33. Best performing course

if "performance_summary" in locals() and "Average_Marks" in performance_summary.columns:
    best_course = performance_summary[
        "Average_Marks"
    ].idxmax()

    best_marks = performance_summary[
        "Average_Marks"
    ].max()

    print("Best Performing Course:", best_course)
    print("Average Marks:", round(best_marks, 2), "%")

# 34. Course with lowest attendance

if "performance_summary" in locals() and "Average_Attendance" in performance_summary.columns:
    lowest_attendance_course = performance_summary[
        "Average_Attendance"
    ].idxmin()

    lowest_attendance = performance_summary[
        "Average_Attendance"
    ].min()

    print(
        "Course with Lowest Attendance:",
        lowest_attendance_course
    )

    print(
        "Average Attendance:",
        round(lowest_attendance, 2),
        "%"
    )

# 35. Final Project Summary

print("=" * 50)
print("STUDENT ANALYTICS SUMMARY")
print("=" * 50)

# Total Students
if "Student Name" in student_df.columns:
    print(
        "Total Students:",
        student_df["Student Name"].nunique()
    )

# Total Records
print(
    "Total Records:",
    len(student_df)
)

# Total Courses
if "Course" in student_df.columns:
    print(
        "Total Courses:",
        student_df["Course"].nunique()
    )

# Average Attendance
if attendance_column is not None:
    print(
        "Average Attendance:",
        round(
            student_df[attendance_column].mean(),
            2
        ),
        "%"
    )

# Average Marks
if marks_column is not None:
    print(
        "Average Marks:",
        round(
            student_df[marks_column].mean(),
            2
        ),
        "%"
    )

# Pass Rate
if "Pass_Fail" in student_df.columns:
    pass_rate = (
        student_df["Pass_Fail"]
        .eq("Pass")
        .mean() * 100
    )

    print(
        "Pass Rate:",
        round(
            pass_rate,
            2
        ),
        "%"
    )

# At-Risk Students
if "At_Risk" in student_df.columns:
    print(
        "At-Risk Records:",
        student_df["At_Risk"].sum()
    )

# ------------------------------------------
# Top Performing Student
# ------------------------------------------

if (
    "Student Name" in student_df.columns
    and marks_column is not None
):

    # Find student with highest marks
    top_student = student_df.loc[
        student_df[marks_column].idxmax()
    ]

    print("\n" + "=" * 50)
    print("TOP PERFORMING STUDENT")
    print("=" * 50)

    print(
        "Student Name:",
        top_student["Student Name"]
    )

    print(
        "Marks:",
        round(
            top_student[marks_column],
            2
        )
    )

    # Show course if available
    if "Course" in student_df.columns:
        print(
            "Course:",
            top_student["Course"]
        )

    # Show attendance if available
    if attendance_column is not None:
        print(
            "Attendance:",
            round(
                top_student[attendance_column],
                2
            ),
            "%"
        )

print("=" * 50)

# 38. Prepare machine learning data

# Find available feature columns
possible_features = [
    "Attendance (%)",
    "Attendance",
    "Mid-Term Marks",
    "Mid Term",
    "End-Term Marks",
    "End Term",
    "Assignment Marks",
    "Assignment",
    "Practical Marks",
    "Practical"
]

features = [
    column for column in possible_features
    if column in student_df.columns
]

print("Features used:")
print(features)

if "At_Risk" in student_df.columns and len(features) >= 2:
    ml_data = student_df[
        features + ["At_Risk"]
    ].dropna()

    X = ml_data[features]
    y = ml_data["At_Risk"]

    print("ML dataset shape:", ml_data.shape)
else:
    print("Not enough data for the ML model.")

# 39. Split data into training and testing sets

if "X" in locals() and len(X) > 1:
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=42
    )

    print("Training data:", X_train.shape)
    print("Testing data:", X_test.shape)

# 41. Make Predictions Using 3 ML Models

if "fitted_models" in globals() and fitted_models:

    print("=" * 50)
    print("PREDICTIONS FROM 3 ML MODELS")
    print("=" * 50)

    for name, (trained_model, _) in fitted_models.items():

        # Make predictions using the correct test data
        predictions = trained_model.predict(
            x_test
        )

        print("\nModel:", name)

        print(
            "First 10 Predictions:"
        )

        print(
            predictions[:10]
        )

else:

    print(
        "No trained models found."
    )

# 42. Check model accuracy

if "predictions" in locals():
    accuracy = accuracy_score(
        y_test,
        predictions
    )

    print(
        "Model Accuracy:",
        round(accuracy * 100, 2),
        "%"
    )

# 42. Check Accuracy of 3 ML Models

if "fitted_models" in globals() and fitted_models:

    print("=" * 50)
    print("MODEL ACCURACY")
    print("=" * 50)

    accuracy_results = []

    for name, (trained_model, _) in fitted_models.items():

        # Make predictions
        predictions = trained_model.predict(
            x_test
        )

        # Calculate accuracy
        accuracy = accuracy_score(
            y_test,
            predictions
        )

        # Save result
        accuracy_results.append({
            "Model": name,
            "Accuracy (%)": round(
                accuracy * 100,
                2
            )
        })

        # Display accuracy
        print(
            name,
            "Accuracy:",
            round(
                accuracy * 100,
                2
            ),
            "%"
        )

    # Create accuracy table
    accuracy_results = pd.DataFrame(
        accuracy_results
    )

    # Sort by accuracy
    accuracy_results = (
        accuracy_results
        .sort_values(
            "Accuracy (%)",
            ascending=False
        )
        .reset_index(
            drop=True
        )
    )

    print("\n" + "=" * 50)
    print("MODEL ACCURACY COMPARISON")
    print("=" * 50)

    display(
        accuracy_results
    )

else:

    print(
        "No trained models found."
    )

"""## Machine Learning — At-Risk Prediction

This section trains and compares **3 Machine Learning models**:

1. **Random Forest**
2. **Gradient Boosting**
3. **Logistic Regression**

The models are compared using **Accuracy**.

"""

# 16. ML — At-Risk Prediction
# Compare 3 Machine Learning Models using Accuracy only

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

TARGET = "At_Risk"

if TARGET not in student_df.columns:
    print("ML skipped: At_Risk target is unavailable.")

else:
    # Select features
    numeric_features = [
        c for c in [
            "Attendance (%)",
            "Mid-Term Marks",
            "End-Term Marks",
            "Assignment Marks",
            "Practical Marks"
        ]
        if c in student_df.columns
    ]

    categorical_features = [
        c for c in ["Course"]
        if c in student_df.columns
    ]

    features = numeric_features + categorical_features

    # Prepare ML data
    ml_data = student_df[
        features + [TARGET]
    ].copy()

    ml_data[TARGET] = pd.to_numeric(
        ml_data[TARGET],
        errors="coerce"
    )

    ml_data = ml_data.dropna(
        subset=[TARGET]
    )

    ml_data = ml_data[
        ml_data[TARGET].isin([0, 1])
    ]

    if len(features) == 0:
        print("ML skipped: no usable features.")

    elif (
        ml_data[TARGET].nunique() < 2
        or len(ml_data) < 10
    ):
        print(
            "ML skipped: not enough data "
            "or class diversity."
        )

    else:
        # Input and target
        X = ml_data[features]
        y = ml_data[TARGET].astype(int)

        # Preprocessing
        preprocessor = ColumnTransformer([
            (
                "num",
                SimpleImputer(
                    strategy="median"
                ),
                numeric_features
            ),
            (
                "cat",
                Pipeline([
                    (
                        "imputer",
                        SimpleImputer(
                            strategy="most_frequent"
                        )
                    ),
                    (
                        "onehot",
                        OneHotEncoder(
                            handle_unknown="ignore"
                        )
                    )
                ]),
                categorical_features
            )
        ])

        # ==========================================
        # CREATE 3 MACHINE LEARNING MODELS
        # ==========================================

        models = {
            "Random Forest": RandomForestClassifier(
                n_estimators=100,
                random_state=42,
                class_weight="balanced"
            ),

            "Gradient Boosting": GradientBoostingClassifier(
                n_estimators=100,
                learning_rate=0.1,
                max_depth=3,
                random_state=42
            ),

            "Logistic Regression": Pipeline([
                (
                    "scale",
                    StandardScaler(
                        with_mean=False
                    )
                ),
                (
                    "model",
                    LogisticRegression(
                        max_iter=1000,
                        class_weight="balanced",
                        random_state=42
                    )
                )
            ])
        }

        # Split data
        x_train, x_test, y_train, y_test = train_test_split(
            X,
            y,
            test_size=0.25,
            random_state=42,
            stratify=y
        )

        # Store results
        model_results = []
        fitted_models = {}

        # ==========================================
        # TRAIN AND TEST ALL 3 MODELS
        # ==========================================

        for name, model in models.items():

            print("\n" + "=" * 60)
            print("MODEL:", name)
            print("=" * 60)

            # Create pipeline
            pipe = Pipeline([
                (
                    "preprocess",
                    preprocessor
                ),
                (
                    "model",
                    model
                )
            ])

            # Train model
            pipe.fit(
                x_train,
                y_train
            )

            # Make predictions
            pred = pipe.predict(
                x_test
            )

            # Calculate accuracy
            accuracy = accuracy_score(
                y_test,
                pred
            )

            # Save result
            model_results.append({
                "Model": name,
                "Accuracy (%)": round(
                    accuracy * 100,
                    2
                )
            })

            # Save trained model
            fitted_models[name] = (
                pipe,
                pred
            )

            # Print accuracy
            print(
                "Accuracy:",
                round(
                    accuracy * 100,
                    2
                ),
                "%"
            )

            # Print classification report
            print("\nClassification Report:")

            print(
                classification_report(
                    y_test,
                    pred,
                    target_names=[
                        "Performing",
                        "At-Risk"
                    ],
                    zero_division=0
                )
            )

        # ==========================================
        # COMPARE THE 3 MODELS
        # ==========================================

        model_results = pd.DataFrame(
            model_results
        )

        model_results = (
            model_results
            .sort_values(
                "Accuracy (%)",
                ascending=False
            )
            .reset_index(
                drop=True
            )
        )

        print("\n" + "=" * 60)
        print("3 MODEL COMPARISON")
        print("=" * 60)

        display(
            model_results
        )

        # ==========================================
        # FIND THE BEST MODEL
        # ==========================================

        best_name = (
            model_results
            .iloc[0]["Model"]
        )

        best_accuracy = (
            model_results
            .iloc[0]["Accuracy (%)"]
        )

        print("\n" + "=" * 60)
        print("BEST MODEL")
        print("=" * 60)

        print(
            "Best Model:",
            best_name
        )

        print(
            "Best Accuracy:",
            best_accuracy,
            "%"
        )

# Confusion Matrix for the 3 ML Models

if "fitted_models" in globals() and fitted_models:

    fig, axes = plt.subplots(
        1,
        len(fitted_models),
        figsize=(5 * len(fitted_models), 4)
    )

    axes = np.atleast_1d(axes)

    for ax, (name, (_, pred)) in zip(
        axes,
        fitted_models.items()
    ):

        cm = confusion_matrix(
            y_test,
            pred,
            labels=[0, 1]
        )

        sns.heatmap(
            cm,
            annot=True,
            fmt="d",
            cmap="Blues",
            xticklabels=[
                "Performing",
                "At-Risk"
            ],
            yticklabels=[
                "Performing",
                "At-Risk"
            ],
            ax=ax
        )

        ax.set_title(name)
        ax.set_xlabel("Predicted")
        ax.set_ylabel("Actual")

    plt.tight_layout()
    plt.show()

else:
    print("No trained ML models are available.")

from pathlib import Path

# Excel file location
FILE_PATH = Path(
    r"C:\Users\YASHANTU AWANA\OneDrive\Desktop\Major\Data.xlsx"
)

print("File path:", FILE_PATH)

# Export cleaned data and ML predictions

OUTPUT_DIR = FILE_PATH.parent / "student_analytics_outputs"

OUTPUT_DIR.mkdir(
    exist_ok=True
)

# Save cleaned data
student_df.to_csv(
    OUTPUT_DIR / "cleaned_student_data.csv",
    index=False,
    encoding="utf-8-sig"
)

# Save predictions from the best model
if "fitted_models" in globals() and fitted_models:

    best_name = model_results.iloc[0]["Model"]

    best_pipe = fitted_models[
        best_name
    ][0]

    student_df[
        "ML_Predicted_AtRisk"
    ] = np.nan

    valid_rows = ml_data.index

    student_df.loc[
        valid_rows,
        "ML_Predicted_AtRisk"
    ] = best_pipe.predict(
        student_df.loc[
            valid_rows,
            features
        ]
    )

    student_df.to_csv(
        OUTPUT_DIR / "student_predictions.csv",
        index=False,
        encoding="utf-8-sig"
    )

    model_results.to_csv(
        OUTPUT_DIR / "model_comparison.csv",
        index=False
    )

    print(
        "Best Model:",
        best_name
    )

    print(
        "Best Accuracy:",
        model_results.iloc[0]["Accuracy (%)"],
        "%"
    )

else:
    print(
        "No trained ML models are available."
    )

print(
    "Outputs saved to:",
    OUTPUT_DIR
)

"""# Project Completed 🎉



"""